/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

/**
 *
 * @author Hal
 */
public class Perfil extends javax.swing.JPanel {

    /**
     * Creates new form Perfil
     */
    public Perfil() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtSearchDistric = new javax.swing.JTextField();
        txtRooms = new javax.swing.JTextField();
        txtPrice = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Perfil");

        txtSearchDistric.setBackground(new java.awt.Color(255, 255, 255));
        txtSearchDistric.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtSearchDistric.setForeground(new java.awt.Color(134, 143, 165));
        txtSearchDistric.setText("Buscar por distrito");
        txtSearchDistric.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(134, 143, 165)));
        txtSearchDistric.setSelectedTextColor(new java.awt.Color(134, 143, 165));
        txtSearchDistric.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchDistricActionPerformed(evt);
            }
        });

        txtRooms.setBackground(new java.awt.Color(255, 255, 255));
        txtRooms.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtRooms.setForeground(new java.awt.Color(134, 143, 165));
        txtRooms.setText("Dormitorios");
        txtRooms.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(134, 143, 165)));
        txtRooms.setSelectedTextColor(new java.awt.Color(134, 143, 165));
        txtRooms.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRoomsActionPerformed(evt);
            }
        });

        txtPrice.setBackground(new java.awt.Color(255, 255, 255));
        txtPrice.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtPrice.setForeground(new java.awt.Color(134, 143, 165));
        txtPrice.setText("Precio");
        txtPrice.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(134, 143, 165)));
        txtPrice.setSelectedTextColor(new java.awt.Color(134, 143, 165));
        txtPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPriceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(440, 440, 440))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(txtSearchDistric, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(txtRooms, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(390, 390, 390))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearchDistric, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRooms, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 277, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(300, 300, 300))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtSearchDistricActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchDistricActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchDistricActionPerformed

    private void txtRoomsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRoomsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRoomsActionPerformed

    private void txtPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPriceActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtRooms;
    private javax.swing.JTextField txtSearchDistric;
    // End of variables declaration//GEN-END:variables
}
